[mukeunzi] 로컬 로그인 구현
code-squad/nodejs-news pull request #19
Opened 2019-07-27 11:38 UTC by mukeunzi

** passport local 로그인 구현**

- 회원가입
- 로그인
- 로그아웃

2019-07-29 08:39 UTC, honux77 commented on README.md
> +<<<<<<< HEAD
컥 충돌 해결 실패!

2019-07-29 08:56 UTC, honux77 commented on models/index.js
> +			`mongodb://${process.env.DB_USERNAME}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/${
connect 메소드 중에 여러 매개변수를 받을 수 있는게 있는지 보고 있으면 그거 쓰는게 좋겠네요.

2019-07-29 08:57 UTC, honux77 commented on models/index.js
> +	mongoose.connection.on('error', error => {
연결 오류가 발생할 경우 서비스가 죽어야 맞을 것 같네요. 실제 디비를 죽이고 잘 되는지 확인해 보세요.

2019-07-29 09:00 UTC, honux77 commented on passport/index.js
> +module.exports = passport => {
시리얼에서 id를 던져주면 deserial에서 다시 디비에서 읽어오는 코드가 있어야 합니다!

2019-07-29 09:04 UTC, honux77 commented on middlewares/login-auth.js
> +const isLoggedOut = (req, res, next) => {
이건 뭔지 모르겠네요? 로그인 상태가 아닌 경우에만 진행하는 것 같은데 그럼 isNotLoggedIn 이 좋을 것 같아요. 
그리고 로그인 상태에는 진입할 수 없는 페이지가 있다는 건 조금 이상하네요.
로그인 페이지가 그렇겠군요 ㅋㅋㅋ

2019-07-29 09:05 UTC, honux77 requested changes
고칠게 조금 있어요.
확인해서 고치고 알려 주세요.

2019-07-29 10:38 UTC, mukeunzi commented on middlewares/login-auth.js
> +const isLoggedOut = (req, res, next) => {
isNotLoggedIn 으로 변경하겠습니다!
지금은 회원가입 페이지, 로그인 페이지에서 사용하고 있어요

2019-08-12 07:44 UTC, honux77 approved these changes
승인!

2019-08-12 07:44 UTC, merged